[project]
name = "jaxtor"
version = "0.2.0-alpha"
description = "JAX-based sampling and evaluation utilities for reinforcement learning environments"
readme = "README.md"
authors = [
    { name = "TolgaOk", email = "tolgaokk@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chex>=0.1.91",
    "jax>=0.8.0",
    "jaxdp @ git+https://github.com/TolgaOk/jaxdp",
    "jaxtyping>=0.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["jaxtor"]

[dependency-groups]
dev = [
    "pyright>=1.1.407",
    "pytest>=9.0.1",
    "ruff>=0.14.5",
]
example = [
    "equinox>=0.13.4",
    "gymnax>=0.0.9",
    "rich>=14.2.0",
    "rlax>=0.1.8",
    "tyro>=1.0.6",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.pytest.ini_options]
markers = [
    "statistical: marks tests as statistical (verify probabilistic properties)",
]

[tool.ruff]
line-length = 88
