[project]
name = "jaxtor"
version = "0.1.0"
description = "JAX-based sampling and evaluation utilities for reinforcement learning environments"
readme = "README.md"
authors = [
    { name = "TolgaOk", email = "tolgaokk@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chex>=0.1.91",
    "distrax>=0.1.7",
    "jax>=0.8.0",
    "jaxtyping>=0.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["jaxtor"]

[dependency-groups]
dev = [
    "pyright>=1.1.407",
    "pytest>=9.0.1",
    "rich>=14.2.0",
    "ruff>=0.14.5",
]
gpu = [
    "jax[cuda12]>=0.8.0",
]
jaxdp = [
    "jaxdp @ git+https://github.com/TolgaOk/jaxdp",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 88
